#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "dark" 

plugins:
  - jekyll-remote-theme 
  - jekyll-include-cache 
  - jekyll-paginate

title: Ø HIT
title-logo: /assets/img/icono.png

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

collections:
  recipes:
    output: true
    permalink: /recipes/:path/
    sort_by: date
    sort_order: reverse

# número de posts por página
paginate: 5
paginate_path: /posts/page:num/


minima:
  skin: dark

name: Alejandro Martinez
  